name: Deploy Render

on:
  push:
    branches:
      - main
  workflow_dispatch: # permite rodar manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Criar deployment
        id: create_deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments \
            -d '{"ref":"main","environment":"production","required_contexts":[],"auto_merge":false}')
          echo "DEPLOYMENT_ID=$(echo $RESPONSE | jq -r '.id')" >> $GITHUB_ENV
          echo "Deployment criado: $DEPLOYMENT_ID"

      - name: Deploy para Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"branch":"main"}' \
            https://api.render.com/deploy/srv-d40cqgemcj7s7390dm00

      - name: Marcar deployment como success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments/$DEPLOYMENT_ID/statuses \
            -d '{"state":"success"}'
