name: Deploy Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Deployment
        uses: peter-evans/create-or-update-deployment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          auto_merge: false
          required_contexts: []

      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"branch":"main"}' \
            https://api.render.com/deploy/srv-d40cqgemcj7s7390dm00
